name: self_contrastive_mwr
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.16
  - numpy==1.23.5
  - scipy==1.10.1
  - pandas==1.5.3
  - scikit-learn==1.2.2
  - matplotlib==3.7.1
  - cudatoolkit==11.8.0
  - pip
  - pip:
      - nvidia-cudnn-cu11==8.6.0
      - tensorflow==2.10.*
      - tensorflow-addons==0.20
  
